- name: variables lo task level variables gurinchi chudam
  hosts: mylovelyhost
  vars:
   sudheer: "oka sodhigadu" #string
   prasadam: #list
   - laddu
   - kaja
   - gulabjam
   brasizes: #mapping or dictionary
    sindhubrasize: 11
    ramyabrasizes: 45
    shermibrasizes: 34
   sizeiscorrect: true # boolean
  tasks:
  - name: now it's time to use all the datatypes 
    ansible.builtin.debug:
     msg: "oka sudheer {{ sudheer }} oka gift ichi {{ prasadam }} valla size telusukuni {{ brasizes }}
              nijama kadha ani {{ sizeiscorrect}}"    

    
