- name: ippudu min and max values chudam
  hosts: mylovelyhost
  become: yes
  tasks:
  - name: let's the item
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
      enabled: yes
    loop:
    - mysql
    - nginx
    - nodejs
