- name: variables gurinchi chudam
  hosts: mylovelyhost
  vars:
    sudheer: sexy
    sindhu: sula
    ramya: kaya
  tasks:
  - name: the variables are not good
    ansible.builtin.debug:
     msg: "chandhu has {{sudheer}} {{sindhu}} koja {{ramya}}"
     