- name: ippudu filters ni chudam
  hosts: mylovelyhost
  tasks:
  - name: "let's see the default value"
    ansible.builtin.debug:
     msg: "this is the value for { lanja | default ('sindhu')}"
 
 

