- name: variables lo task level variables gurinchi chudam
  hosts: mylovelyhost
  vars_files:
  - pukugadu.yaml
  tasks:
  - name: let's see how we can vars variables
    ansible.builtin.debug:
     msg: " here we see sudheer {{ sudheer }} and lick the {{ sidhu }} and {{ ramya }} and piskutha {{ shermi}} "
  
