- name: ippudu min and max values chudam
  hosts: mylovelyhost
  vars:
   sudheergadu:
   - {'key': 'dog', 'value': 'animal'}
   - {'key': 'sindhu', 'value': 'lovelyfigure'}
   - {'key': 'ramya', 'value': 'No figure'}
 
    
  tasks:
  - name: before convert to the items
    ansible.builtin.debug:
      msg: "the dictionary is {{sudheergadu}} "

  - name: After converting into list
    ansible.builtin.debug:
      msg: "coverting into dictionany {{ sudheergadu| items2dict}}"
