- name: ippudu min and max values chudam
  hosts: mylovelyhost
  vars:
   sudheerages: [24,45,67,87,89,90,3,65,23,32,21,33,51,34,44,55,89,01,91,02]
  tasks:
  - name: the minimum values will be
    ansible.builtin.debug:
      msg: "min ages: {{ sudheerages| min }} , maxages: {{ sudheerages| max}}"

