- name: ippudu conditions ne chudam
  hosts: mylovelyhost
  become: yes
  tasks: 
  - name: linux command ala use cheyalo chudam
    ansible.builtin.command: id sexysindhu
    ignore_errors: true
    register: sexy
  - name: ippudu error message store chedam
    ansible.builtin.debug:
     msg: "error message ni store chey jako {{ sexy }}"
  - name: user sexysindhu ni add chedam
    ansible.builtin.command: useradd sexysindhu
    when: sexy.rc != 0 #condition ra
  - name: normal message
    ansible.builtin.debug:
     msg: " message normally"
 

