- name: variables lo task level variables gurinchi chudam
  hosts: mylovelyhost
  tasks:
  - name: ippudu chudam variables ala read avuthayo
    ansible.builtin.debug:
     msg: "here we use the values {{ naveena }} {{ ramya }} {{ tanuja }}"
    
