- name: variables lo task level variables gurinchi chudam
  hosts: mylovelyhost
  become: yes
  tasks:
  - name: idam oka linux command
    ansible.builtin.command: id sodhigadu
    ignore_errors: true
    register: vinni
  
  - name: error message ni store chedam
    ansible.builtin.debug:
     msg: "store error message {{ vinni }}"  
  
  - name: chudam ra piggy
    ansible.builtin.debug:
     msg: " adho oka sodhi"


