- name: ippudu filters ni chudam
  hosts: mylovelyhost
  vars_prompt:
    - name: sodhigadu
      prompt: please enter the number
      private: no
  tasks:
  - name: let's see how we can do it
    ansible.builtin.debug:
     msg: "the given number is {{ sodhigadu }}"
    when: sodhigadu | int > 10

  - name: what if we give less than 10
    ansible.builtin.debug:
     msg: "the given number is {{ sodhigadu }}"
    when: sodhigadu | int <= 10
 
 

