- name: ippudu min and max values chudam
  hosts: mylovelyhost
  become: yes
  tasks:
  - name: let's the item
    ansible.builtin.dnf:
      name: "{{ item.name}}"
      state: " {{item.state}}"
    loop:
    - { name: 'mysql', state: 'present' }
    - { name: 'nginx', state: 'absent' }
    - { name: 'nodejs', state: 'present' }
