- name: variables lo task level variables gurinchi chudam
  hosts: mylovelyhost
  vars_prompt:
  - name: wastecandidate
    prompt: please enter the username
    private: no
  - name: worstcandidate
    prompt: please enter the password
    private: true
  tasks:
  - name: enter the given info please
    ansible.builtin.debug:
     msg: "the username is {{wastecandidate}} and the password is {{ worstcandidate }}"
