- name: variables lo task level variables gurinchi chudam
  hosts: mylovelyhost
  vars_files:
  - shermilanja.yaml
  tasks:
  - name: let see our god names
    ansible.builtin debug:
     msg: "this was the shiva for {{ shiva }} and vishnu for {{ vishnu }} other god lakshmi for {{ lakshmi }}"
