- name: we will install the nginx and run it
  hosts: mylovelyhost
  become: yes
  tasks:
  - name: install the ngnix
    ansible.builtin.dnf:
     name: ngnix
     state: latest
  - name: run the nginx
    ansible.builtin.service:
     name: ngnix
     state: started
     enabled: yes