- name: idhi first atta
  hosts: mylovelyhosts
  tasks:
  - name: idhi na first atta
    ansible.builtin.debug:
     msg: "this is sex with alekhya"

- name: idhi na second atta
  hosts: mylovelyhosts
  tasks:
  - name: idhi na second atta
    ansible.builtin.debug:
     msg: "this is sex with sindhura. nee puku ni nakalani vundhi"